---
abstract: 'Check code for FIXMEs.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Fixme
requires:
  perl: v5.6.2
resources:
  bugtracker: https://github.com/plicease/test-fixme/issues
  homepage: http://search.mcpan.org/dist/Test-Fixme
  repository: git://github.com/plicease/test-fixme.git
version: '0.11'
