---
abstract: 'check code for FIXMEs.'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Fixme
requires:
  Carp: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::Manifest: 0
  File::Find: 0
  Test::Builder: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/plicease/test-fixme/issues
  homepage: http://search.mcpan.org/dist/Test-Fixme
  repository: git://github.com/plicease/test-fixme.git
version: 0.10
